//
// AddRestaurantRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Add a restaurant to a community */
public struct AddRestaurantRequest: Codable, Hashable {

    public var restaurantId: Int64

    public init(restaurantId: Int64) {
        self.restaurantId = restaurantId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case restaurantId = "restaurant_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(restaurantId, forKey: .restaurantId)
    }
}

