//
// AuthVendor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AuthVendor: String, Codable, CaseIterable {
    case google = "Google"
    case apple = "Apple"
    case anonymous = "Anonymous"
}
