//
// Bookmark.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Represents many to many relationsip of bookmark between users and communities */
public struct Bookmark: Codable, Hashable {

    public var userId: Int64
    public var communityId: Int64

    public init(userId: Int64, communityId: Int64) {
        self.userId = userId
        self.communityId = communityId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case communityId = "community_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(communityId, forKey: .communityId)
    }
}

