//
// CommunityDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CommunityDetail: Codable, Hashable {

    public var id: Int64
    public var name: String
    public var description: String?
    public var location: Location?
    public var userCount: Int
    public var numRestaurant: Int?

    public init(id: Int64, name: String, description: String? = nil, location: Location? = nil, userCount: Int, numRestaurant: Int? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.location = location
        self.userCount = userCount
        self.numRestaurant = numRestaurant
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case location
        case userCount = "user_count"
        case numRestaurant = "num_restaurant"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encode(userCount, forKey: .userCount)
        try container.encodeIfPresent(numRestaurant, forKey: .numRestaurant)
    }
}

