//
// GetCommunityIdTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetCommunityIdTokenResponse: Codable, Hashable {

    public var inviteToken: String
    /** Token dulation (seconds) */
    public var expiresIn: Int

    public init(inviteToken: String, expiresIn: Int) {
        self.inviteToken = inviteToken
        self.expiresIn = expiresIn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inviteToken = "invite_token"
        case expiresIn = "expires_in"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(inviteToken, forKey: .inviteToken)
        try container.encode(expiresIn, forKey: .expiresIn)
    }
}

