//
// JoinCommunityRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JoinCommunityRequest: Codable, Hashable {

    public var communityId: Int64

    public init(communityId: Int64) {
        self.communityId = communityId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case communityId = "community_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(communityId, forKey: .communityId)
    }
}

