//
// ListCommunityUsersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListCommunityUsersResponse: Codable, Hashable {

    public var id: Int64
    public var name: String
    public var profileImageUrl: String?
    public var users: [User]?

    public init(id: Int64, name: String, profileImageUrl: String? = nil, users: [User]? = nil) {
        self.id = id
        self.name = name
        self.profileImageUrl = profileImageUrl
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case profileImageUrl = "profile_image_url"
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(profileImageUrl, forKey: .profileImageUrl)
        try container.encodeIfPresent(users, forKey: .users)
    }
}

