//
// SearchCommunityResponseAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchCommunityResponseAllOf: Codable, Hashable {

    public var communities: [Community]?

    public init(communities: [Community]? = nil) {
        self.communities = communities
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case communities
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(communities, forKey: .communities)
    }
}

