//
// UpdateCommentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update private comments for a restaurant */
public struct UpdateCommentRequest: Codable, Hashable {

    public var body: String?

    public init(body: String? = nil) {
        self.body = body
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(body, forKey: .body)
    }
}

