//
// UserDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserDetail: Codable, Hashable {

    public var id: Int64
    public var name: String
    public var profileImageUrl: String?
    public var communityCount: Int
    public var bookmarkCount: Int

    public init(id: Int64, name: String, profileImageUrl: String? = nil, communityCount: Int, bookmarkCount: Int) {
        self.id = id
        self.name = name
        self.profileImageUrl = profileImageUrl
        self.communityCount = communityCount
        self.bookmarkCount = bookmarkCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case profileImageUrl = "profile_image_url"
        case communityCount = "community_count"
        case bookmarkCount = "bookmark_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(profileImageUrl, forKey: .profileImageUrl)
        try container.encode(communityCount, forKey: .communityCount)
        try container.encode(bookmarkCount, forKey: .bookmarkCount)
    }
}

